COMMON: &common #标识
  DEBUG: False
  SECRET_KEY: mdd1##$$%^!DSA#FDSF
  # 数据库环境的配置
  SQLALCHEMY_DATABASE_URI: "mysql://root:xjh199923@127.0.0.1:3306/realEstate"
  SQLALCHEMY_TRACK_MODIFICATIONS: True
  SQLALCHEMY_ECHO: True

DEVELOPMENT: &development
  <<: *common # 继承common，没有重新定义的变量，使用common变量值
  DEBUG: True

STAGING: &staging
  <<: *common
  SECRET_KEY: sortasecure

PRODUCTION: &production
  <<: *common
